version: '3'

volumes:
    pgadmin:
    postgres:

services:

    pgadmin:
        container_name: p-pgadmin
        image: dpage/pgadmin4
        restart: unless-stopped

        environment:
            PGADMIN_DEFAULT_EMAIL: ryan-aristosa@host.com
            PGADMIN_DEFAULT_PASSWORD: ryan-aristosa

        volumes:
            - pgadmin:/root/.pgadmin

        ports:
            - '8080:8080'

    postgres:
        container_name: p-postgres
        image: postgres
        environment:
            POSTGRES_USER: ryan-aristosa
            POSTGRES_PASSWORD: ryan-aristosa
            PGDATA: /data/postgres

        volumes:
            - postgres:/data/postgres

        ports:
            - '5432:5432'

        restart: unless-stopped